#!/usr/bin/env python
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from meander_morphology.clustering import cluster_latent_space, label_names
from meander_morphology.latent import encode_spectra
from meander_morphology.model import build_encoder_from_autoencoder, load_autoencoder
from meander_morphology.plotting import plot_latent_space


def load_spectra(path: Path) -> np.ndarray:
    if path.is_file() and path.suffix == ".npy":
        return np.load(path)
    raise ValueError("Use --spectra with a spectra.npy file generated by extract_single_bends.py")


def main() -> None:
    parser = argparse.ArgumentParser(description="Classify single bends using the autoencoder latent space.")
    parser.add_argument("--spectra", type=Path, required=True, help="spectra.npy generated by extract_single_bends.py")
    parser.add_argument("--model", type=Path, required=True, help="Keras .h5 autoencoder model")
    parser.add_argument("--output", type=Path, required=True, help="Output directory")
    parser.add_argument("--clusters", type=int, default=3)
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    spectra = load_spectra(args.spectra)
    autoencoder = load_autoencoder(args.model)
    encoder = build_encoder_from_autoencoder(autoencoder, latent_dim=2)
    latent = encode_spectra(encoder, spectra)
    np.save(args.output / "latent_coordinates.npy", latent)

    result = cluster_latent_space(latent, n_clusters=args.clusters)
    np.save(args.output / "cluster_centers.npy", result.centers)
    np.save(args.output / "cluster_labels.npy", result.labels)

    rows = pd.DataFrame(
        {
            "bend_id": np.arange(len(result.labels)),
            "latent_1": latent[:, 0],
            "latent_2": latent[:, 1],
            "cluster": result.labels,
            "cluster_name": label_names(result.labels),
        }
    )
    rows.to_csv(args.output / "classification.csv", index=False)
    plot_latent_space(latent, result.labels, args.output / "latent_space.png")
    print(f"Saved classification outputs to {args.output}")


if __name__ == "__main__":
    main()
